server:
  port: 8222

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # default false
          lowerCaseServiceId: true
      routes:
        - id: students-service-route
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools-service-route
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
  config:
    import: optional:configserver:http://localhost:8888