server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: student
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students_db
    username: shrikant
    password: kale
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        database: postgresql
        dialect: org.hibernate.dialect.PostgreSQLDialect